### ISSUE TITLE
Unable to access to React front end with custom URL 

### ISSUE THREAD

**Issue by natfirst** [cuba-platform/uberjar#10]
Environment

- Platform version: 7.2.11
- Forum issue: https://www.cuba-platform.com/discuss/t/confusion-deploying-react-uberjar-url/14751

### Description of the bug or enhancement

1. Create a small project
2. Add React front module
3. Set up single UberJar task
4. Try to run the application from the command line using frontContextName command line argument (see [docs](https://doc.cuba-platform.com/manual-latest/uberjar_deployment.html))
E.g. `java -jar app.jar -frontContextName sales`

*A.R.* React front-end will not be available by http://localhost:8080/sales

5. Change `PUBLIC_URL` variable in `.env.production.local`
6. Start UberJar

*A.R.* React front-end will not be available

**Comment by andreysubbotin** [comment]
Won't fix. UberJar doesn't work correctly with `frontContextName`, `contextName` properties with React frontend client. Add restrictions into the documentation cuba-platform/documentation#781.
