### ISSUE TITLE
Encoding issues with freemarker (front)

### ISSUE THREAD

**Issue by web-devel** [cuba-platform/uberjar#11]
Cyrillic symbols in front module's `index.html` are being converted to question marks when served via uberJar.

For the front module we convert `index.html` to freemarker template `index.ftl` in order to make some runtime processing.
It seems freemarker is not configured to work with UTF encoding, e.g.:
```
  <init-param>
    <param-name>ContentType</param-name>
    <param-value>text/html; charset=UTF-8</param-value> 
  </init-param>
```

**Comment by andreysubbotin** [comment]
Test case:
- Create react front module
- Add Russian characters into the `<title>` tag in the file `public/index.html`
- Build and run Uber Jar
- Open the front client in a browser. Check that tab caption contains Russian characters

**Comment by skatova** [comment]
![image](https://user-images.githubusercontent.com/53561930/109159178-c4c0dd00-778d-11eb-9edd-e7e05cdbb103.png)
[testuberjar.zip](https://github.com/cuba-platform/uberjar/files/6043208/testuberjar.zip)
