### ISSUE TITLE
Update jetty version

### ISSUE THREAD

**Issue by web-devel** [cuba-platform/uberjar#9]
Consider update version of jetty (at least bugfix) as currently rather old is used: jetty-9.4.19 Jun 10, 2019 
https://github.com/eclipse/jetty.project/releases

**Comment by glebshalyganov** [comment]
Update of jetty is needed to fix the issue in SAML add-on: https://github.com/cuba-platform/saml-addon/issues/25 regarding SameSite=None cookie attribute.

**Comment by andreysubbotin** [comment]
For QA: smoke test UberJar + websocket tests
